// <auto-generated />
using System;
using ChangFuPOS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChangFuPOS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260530050327_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ChangFuPOS.Models.PriceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly>("PriceDate")
                        .HasColumnType("date");

                    b.Property<int>("RiceTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("RiceTypeId", "PriceDate")
                        .IsUnique();

                    b.ToTable("PriceLogs");
                });

            modelBuilder.Entity("ChangFuPOS.Models.RiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("RiceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "蓬萊米 (濕)"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "在來米 (濕)"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "蓬萊米 (乾)"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "在來米 (乾)"
                        });
                });

            modelBuilder.Entity("ChangFuPOS.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ExceptionReason")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FarmerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("GrossWeightKg")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsException")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("NetWeightJin")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("NetWeightKg")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("PriceSnapshot")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("RiceTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("TareWeightKg")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("TicketNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("VehicleNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Village")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RiceTypeId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("ChangFuPOS.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            PasswordHash = "$2a$11$0iY6TxmPp3qiJ9lYmzTtGOo4QZt5pZke5kO5ynibg2OD28CgW/X6G",
                            Role = "admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            PasswordHash = "$2a$11$UHZiYmiN0CHLZnmWuiID..U5FtmZJwpGZuKKLDq5gc89L4Z4Z7ZdS",
                            Role = "cashier",
                            Username = "cashier"
                        });
                });

            modelBuilder.Entity("ChangFuPOS.Models.PriceLog", b =>
                {
                    b.HasOne("ChangFuPOS.Models.RiceType", "RiceType")
                        .WithMany("PriceLogs")
                        .HasForeignKey("RiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RiceType");
                });

            modelBuilder.Entity("ChangFuPOS.Models.Ticket", b =>
                {
                    b.HasOne("ChangFuPOS.Models.RiceType", "RiceType")
                        .WithMany("Tickets")
                        .HasForeignKey("RiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RiceType");
                });

            modelBuilder.Entity("ChangFuPOS.Models.RiceType", b =>
                {
                    b.Navigation("PriceLogs");

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
